version: '3.3'

networks: 
  internal:
    external: false
  proxy:
    external: true

# volumes: 
#   dentrist:
#     driver: rexray

services:

  # internal ports = 80, 443
  nodejs:
    image: myuserindocker/naefswiss-webapp:latest
    environment:
      DEPLOYMENT: production
      HOST: naefswiss.webapp.run
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - internal
      - proxy
  
  # internal port = 8080
  rethinkdb:
    image: rethinkdb:2.3.6
    volumes:
      - "/mnt/datadisk-1/naefswiss/rethinkdbData:/data/rethinkdb_data/"
    networks:
      - internal
      - proxy
